name: Build LaTeX document
on: [push, fork]
jobs:
  build_latex:
    name: Build
    runs-on: ${{matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Pub_bwHPC_Symposium_2023.Jonas-Pleyer-Version-01.tex
          latexmk_shell_escape: true
          args: -pdf -shell-escape

      - name: Upload main.pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: main.pdf
          path: main.pdf
  
  release_pdf:
    name: Release PDF
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: main.pdf

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Pub_bwHPC_Symposium_2023.Jonas-Pleyer-Version-01.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
