name: Build LaTeX document
on: push

env:
  main: Pub_bwHPC_Symposium_2023.Jonas-Pleyer-Version-01
jobs:
  build_latex:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.main }}.tex
          latexmk_shell_escape: true
          args: -pdf -shell-escape

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.main }}.pdf
          path: ${{ env.main }}.pdf
  
  release_pdf:
    name: Release PDF
    needs: build_latex
    runs-on: ubuntu-latest
    permissions:
      content: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.main }}.pdf

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.main }}.pdf
          token: $${{ secrets.GITHUB_TOKEN }}
          commit: main
          tag: main
